const FenceTypes = [
    { name: "Standard", image: "https://greenviewsolutionsimages.s3.us-west-1.amazonaws.com/gvsnextimages/globalimages/fencingRenders/wStandardCornerPartial.png", description: "Picket fences are a classic and charming fencing style, distinguished by evenly spaced vertical boards, or 'pickets,' attached to horizontal rails. These fences are often shorter than privacy fences and are widely recognized for their picturesque, traditional appearance, commonly associated with the classic American dream home. Picket fences are available in various materials, including wood and vinyl, and are often painted white, although they can be customized in different colors. They are ideal for decorative purposes and for delineating property boundaries without obstructing views."},
    { name: "Open Picket", image: "https://greenviewsolutionsimages.s3.us-west-1.amazonaws.com/gvsnextimages/globalimages/fencingRenders/wSpacedPickets.png", description: "Horizontal! fences are a modern and stylish fencing option characterized by parallel boards laid flat across the posts. This design contrasts with the traditional vertical fence style, offering a sleek and contemporary look. Horizontal fences are known for their clean lines and can make a space appear larger and more open. They are versatile in design, allowing for various board spacing and sizes, which can be customized to achieve different levels of privacy and aesthetic appeal. This type of fence is particularly popular in modern home landscaping and urban design." },
    { name: "Horizontal", image: "https://greenviewsolutionsimages.s3.us-west-1.amazonaws.com/gvsnextimages/globalimages/fencingRenders/wStandardHorizontal.png", description: "A shadowbox fence features an alternating pattern of boards, with one board placed on one side of the fence rail and the next on the opposite side, creating a shadow effect. This design offers privacy while still allowing air circulation, making it both functional and aesthetically pleasing." },
    { name: "Board On Board", image: "https://greenviewsolutionsimages.s3.us-west-1.amazonaws.com/gvsnextimages/globalimages/fencingRenders/wPartialCornerBOBPremium.png", description: "A board on board fence is a design where wooden boards are overlapped, creating an aesthetically pleasing and privacy-enhancing structure. This fence style offers a seamless look since the overlapping boards cover any gaps that might widen over time due to weather or shifting. It's a popular choice for those seeking both privacy and a visually appealing boundary. The construction of a board on board fence also provides good wind resistance due to the alternating board pattern." },
    { name: "Ranch Rail", image: "https://greenviewsolutionsimages.s3.us-west-1.amazonaws.com/gvsnextimages/globalimages/fencingRenders/wStandardPostandDowell.png", description: "The Stockade fence is known for its solid, closely-spaced vertical boards, providing a high level of privacy and security. This classic design is often used in residential areas and is particularly effective in offering a secluded and private environment." },
   
];

export default FenceTypes;